// src/config/interests.ts
// Enthält die Liste der verfügbaren Interessen für den Onboarding-Schritt.

export const availableInterests: string[] = [
  "Açaí", "Achtsamkeit", "Actionfilme", "Aktivismus", "Aktiver Lebensstil",
  "Alternative-Musik", "Amateur Cook", "American Football", "Among Us", "Angeln",
  "Animationsfilme", "Anime", "Aquarium", "Astrologie", "Atari",
  "Austauschprogramme", "Ausstellungen", "Autokino", "Autorennen", "Autos",
  "BBQ", "Backen", "Backpacking", "Badminton", "Ballett", "Bar-Hopping",
  "Bars", "Baseball", "Basketball", "Bass spielen", "Beach-Sportarten",
  "Beach-Tennis", "Beachvolleyball", "Berge", "Black Lives Matter", "Blackpink",
  "Blogging", "Bodycombat", "Bodyjam", "Bodypump", "Bodystep", "Bogenschießen",
  "Bollywood", "Bowling", "Boxen", "Börsenhandel", "Brunch", "Brettspiele",
  "Broadway", "Bubble Tea", "BTS", "Café-Hopping", "Caipirinha", "Camping",
  "Catan", "Cheerleading", "Chor", "Clubbing", "Cocktails", "Comedy",
  "Comic-Conventions", "Content Creation", "Cosplay", "Couchsurfing",
  "Craft Beer", "Cricket", "Crossfit", "DIY", "DAOs", "Dokus", "Drama-Serien",
  "Dungeons & Dragons", "EDM", "E-Sport", "Eis", "Eishockey",
  "Elektronische Musik", "Escape Rooms", "Fantasy-Filme", "Felsenklettern",
  "Feminismus", "Festivals", "Filme", "Filmfestivals", "Five-a-side Football",
  "Fitness", "Fitnessstudio", "Flag Football", "Flamenco", "Folk-Musik",
  "Food-Touren", "Foodie", "Fortnite", "Fotografie", "Free Diving",
  "Freelance arbeiten", "Funk Music", "Fußball", "Fünfkampf", "Gartenarbeit",
  "Gassi gehen", "Geisterfilme", "Gesellschaftliche Entwicklung", "Gewichtheben",
  "Gin Tonic", "Gitarre spielen", "Gleichberechtigung", "Gospelmusik", "Grime",
  "Gymnastik", "Happy Hour", "Harry Potter", "Hautpflege", "Heavy Metal",
  "Hip-Hop", "Hockey", "Home-Workouts", "Hot Yoga", "House-Musik",
  "House-Partys", "Iced Tea", "Immobilien", "Indie-Filme", "Indie-Musik",
  "Inlineskating", "Instagram", "Investing", "J-Pop", "Jazz", "Jetski fahren",
  "Joggen", "Judo", "Jugendbewegungen", "Jujitsu", "K-Drama-Serien", "K-Pop",
  "Kaffee", "Kaffeebuden", "Kanufahren", "Karaoke", "Karate", "Kind der 90er",
  "Klimawandel", "Kochen", "Komponieren", "Konzerte", "Koreanisches Essen",
  "Krimis", "Kunst", "Kunstgalerien", "Kunstturnen", "LGBTQIA+ Rechte",
  "Laufen", "League of Legends", "Leichtathletik", "Lesen", "Liebeskomödien",
  "Literatur", "Live-Musik", "MLB", "Make-up", "Malen", "Manga", "Marathon",
  "Martial Arts", "Marvel", "Meditieren", "Memes", "Menschenrechte", "Metaverse",
  "Mocktails", "Mode", "Motorsport", "Motorradfahren", "Motorradrennen",
  "Motorräder", "Muay Thai", "Museen", "Musik", "Musikbands", "Musikinstrumente",
  "Musicals", "NBA", "NFTs", "Nachtleben", "Natur", "Netflix",
  "Neue Sachen ausprobieren", "Nintendo", "Online-Games", "Online-Shopping",
  "Oper", "Outdoor", "Padel", "Paddelboarding", "Paragliding", "Partys",
  "Pflanzen", "Pho", "Picknick", "Pilates", "Pimms", "Pinterest", "PlayStation",
  "Podcasts", "Poetry", "Pole-Dancing", "Politik", "Pop-Musik", "Potterhead",
  "Pride", "Pub Quiz", "Pubs", "Punk-Musik", "R&B", "Rad fahren", "Radrennen",
  "Ramen", "Rap-Musik", "Raves", "Reality-TV", "Rechte von Behinderten",
  "Reggaeton", "Reisen", "Reitsport", "Relaxen in der Bar",
  "Rhythmische Sportgymnastik", "Road Trips", "Roblox", "Rockmusik",
  "Rollschuhlaufen", "Rudern", "Rugby", "Sake", "Samba", "Sauna",
  "Saxophon spielen", "Schlagzeug spielen", "Schlittschuhfahren", "Schreiben",
  "Schweinebraten", "Schwimmen", "Sci-Fi", "Second-Hand-Shopping",
  "Seelische Gesundheit", "Segeln", "Selbstentwicklung", "Selbstliebe",
  "Self Care", "Shisha", "Shopping", "Singen", "Skateboarden", "Skaten",
  "Skifahren", "Slam Poetry", "Sneaker", "Snowboarden", "Social Media",
  "Songwriting", "Soul-Musik", "SoundCloud", "Spa", "Sport", "Sportprogramme",
  "Sportschießen", "Spotify", "Sprachaustausch", "Stadtfeste",
  "Stand-up-Comedy", "Start-ups", "Strandbars", "Street Food", "Surfen",
  "Sushi", "Synchronschwimmen", "Süße Leckereien", "TV-Serien bingen",
  "Taekwondo", "Tango", "Tanzen", "Tarot", "Tattoos", "Tauchen", "Tee",
  "Techno", "Tennis", "Theater", "Thermalbäder", "Thriller", "TikTok",
  "Tischtennis", "Trap Music", "Triathlon", "Trivia", "Twitch", "Twitter",
  "Umweltaktivismus", "Umweltschutz", "Unternehmertum", "Upcycling",
  "Veganes Kochen", "Vermut", "Vinyasa", "Vintage-Mode", "Virtual Reality",
  "Vlogging", "Voguing", "Volleyball", "Volunteering", "Wahlrechte", "Walking",
  "Walking-Touren", "Wandern", "Wein", "Weltfrieden", "West End Musicals",
  "Wrestling", "Xbox", "Yoga", "YouTube", "Zeichnen"
];
