// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjvwjddbbbietaewzbne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdndqZGRiYmJpZXRhZXd6Ym5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzk0MzcsImV4cCI6MjA1MzkxNTQzN30.9bPGjA_VDFZXeS_LJ9wZt-IwNDTkz21WEfGEZ2-0Acg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);